---
##
consul1:
  image: mmochan/consul
  hostname: consul1
  container_name: consul1
  ports:
   - "8301:8300"
   - "8401:8400"
   - "8501:8500"
   - "8601:8600"
   - "9001:9001"
  environment:
   - CONSUL_OPTS=-bootstrap-expect=3 -ui

consul2:
  image: mmochan/consul
  hostname: consul2
  container_name: consul2
  links:
   - consul1
  ports:
   - "8302:8300"
   - "8402:8400"
   - "8502:8500"
   - "8602:8600"
   - "9002:9001"
  environment:
   - CONSUL_OPTS=-rejoin -retry-join=consul1

consul3:
  image: mmochan/consul
  hostname: consul3
  container_name: consul3
  links:
   - consul1
  ports:
   - "8303:8300"
   - "8403:8400"
   - "8503:8500"
   - "8603:8600"
   - "9003:9001"
  environment:
   - CONSUL_OPTS=-rejoin -retry-join=consul1
